<?php


/**
 * Implements hook_menu().
 * Создаётся страница, на которой размещается форма.
 */
function gf_user_create_menu() {
  $items['gf-user/create'] = array(
    'title' => t('Create account for new client'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['user_create_form'],
    'access arguments' => array('gf user create'),
  );

  return $items;
}


/**
 * Форма создания нового клиента.
 */
function user_create_form() {
  $form = array();

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#placeholder' => t('Name of the Customer or Company name'),
  );
  $form['phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone'),
    '#placeholder' => '9012345678',
    /*'#prefix' => '+7',*/
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => 'e-mail',
    '#placeholder' => 'name@example.com',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Create new account'),
  );

  return $form;
}

/**
 * @param $form
 * @param $form_state
 *
 * Валидация данных, ввнедённых в форму
 */
function user_create_form_validate($form, $form_state) {
  if(empty($form_state['values']['phone'])){
    form_set_error('phone', t('Phone number must be set'));
  } /*elseif ($form_state['values']['phone']){
    form_set_error('phone', t('Phone number must be set'));
  }*/
}

/**
 * @param $form
 * @param $form_state
 *
 * @throws \Exception
 *
 * При отправке формы производятся следующие действия:
 * 1. создание нового пользователя с ролью "Оптовый клиент
 * 2. переключение на этого пользователя средствами masquerade
 * 3. переадресация на страницу каталога товаров
 */
function user_create_form_submit($form, $form_state) {
  $phone = trim($form_state['values']['phone']);
  $phone_plain = str_replace(array('(',')',' ','-'),'',$phone);
  $manager_user = user_load($GLOBALS["user"]->uid);
  $manager_nid = $manager_user->field_manager["und"][0]["target_id"];


  if(empty($form_state['values']['name'])) {
    $name = $phone;
  } else {
    $name = $form_state['values']['name'];
  }


  if (empty($form_state['values']['email'])) {
    $email = 'customer+' . $form_state['values']['phone'] . '@giorgio-ferretti.it';
  } else {
    $email = $form_state['values']['email'];
  }


  $new_customer = array(
    'name'	=> $phone_plain,
    'pass'	=> $phone_plain, // note: do not md5 the password
    'mail'	=> $email,
    'language' => 'ru',
    'field_kompaniya'=>['und' => [0 => ['value' => $form_state['values']['name']]]],
    'field_telefon' => ['und' => [0 => ['value' => $phone]]],
    'timezone' => 'Europe/Moscow',
    'field_firstname' => ['und'=>[0=>['value'=>$name]]],
    'field_macroregion'=>["und"=>[0=>["value"=>'Russia']]],
    'field_country_name'=>["und"=>[0=>["value"=>'RU']]],
    'field_language_pref'=>["und"=>[0=>["value"=>'ru']]],
    'field_manager'=>["und"=>[0=>["target_id"=>$manager_nid]]],
    'status' => 1,
    'init' => $email,
    'roles' => array(
      DRUPAL_AUTHENTICATED_RID => 'authenticated user',
      19 => 'Wholesale customer',
    ),
  );


  // The first parameter is null so a new user is created.
  $new_user = user_save(null, $new_customer);
  //$new_user->password = $new_customer['pass'];
  _user_mail_notify('register_admin_created', $new_user);
  masquerade_switch_user($new_user->uid);
  drupal_goto('gf_stock/region_switch/Russia', array('query'=>array('destination'=>'shop')));
}

/**
 * Implements hook_permission().
 */
function gf_user_create_permission() {
  return [
    'gf user create' => [
      'title' => t('Create new customer'),
      'description' => t('Create new wholesaler customer from simple form'),
    ],
  ];
}

